import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SceneComponent from "../components/scene/scene";


export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>ThreeJS</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <SceneComponent/>
        </div>
    )
}
